### ISSUE TITLE
Web 页面打印一些知识点整理

### ISSUE THREAD

**Issue by Gavinchen92** [Gavinchen92/blog#11]
# Web 页面打印的新知识点

### @media print 

link元素上面可以设置media=“print”
这样做的好处是不会阻塞页面的首次渲染
```html
<link rel="stylesheet" href="print.css" media="print" />
```

### 单位pt

是专门用于打印媒体的标准长度单位，它的优点是在不同的设备上显示的效果更佳一致

### @page 🚀

 可以在css中设置打印页面的一些属性，如纸张尺寸，边距等等
```css
@page {
  size: A4 landscape;
  margin: 2cm;
}
```

### -webkit-print-color-adjust: exact

设置打印背景图形
